### ISSUE TITLE
[11.0] Assets don't work with --workers

### ISSUE THREAD

**Issue by yelizariev** [odoo/docker#132]
Steps to reproduce:

    docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name db-odoo postgres:9.5
    docker run --rm -p 8069:8069 --link db-odoo:db odoo:11.0 -- --workers=1 -d odoo-11
 

Now open http://localhost:8069 . At browser console:

     GET http://localhost:8069/web/content/251-a8faf6d/web.assets_frontend.0.css net::ERR_CONTENT_LENGTH_MISMATCH

Trying via wget:

```

wget  http://localhost:8069/web/content/252-8df9d31/web.assets_common.js
--2017-10-26 13:14:13--  http://localhost:8069/web/content/252-8df9d31/web.assets_common.js
Resolviendo localhost (localhost)... 127.0.0.1
Conectando con localhost (localhost)[127.0.0.1]:8069... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 903052 (882K) [application/javascript]
Grabando a: “web.assets_common.js”

web.assets_common.js                                17%[==================>                                                                                              ] 154.13K  --.-KB/s    in 0s      

2017-10-26 13:14:13 (613 MB/s) - Conexión cerrada en el byte 157832. Reintentando.

--2017-10-26 13:14:14--  (intento: 2)  http://localhost:8069/web/content/252-8df9d31/web.assets_common.js
Conectando con localhost (localhost)[127.0.0.1]:8069... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 903052 (882K) [application/javascript]
Grabando a: “web.assets_common.js”

web.assets_common.js                                22%[========================>                                                                                        ] 195.14K  --.-KB/s    in 0.001s  

2017-10-26 13:14:14 (186 MB/s) - Conexión cerrada en el byte 199824. Reintentando.

--2017-10-26 13:14:16--  (intento: 3)  http://localhost:8069/web/content/252-8df9d31/web.assets_common.js
Conectando con localhost (localhost)[127.0.0.1]:8069... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 903052 (882K) [application/javascript]
Grabando a: “web.assets_common.js”

web.assets_common.js                                21%[======================>                                                                                          ] 185.24K  --.-KB/s    in 0s      

2017-10-26 13:14:16 (1.62 GB/s) - Conexión cerrada en el byte 199824. Reintentando.


```

**The problem is not reproduced with odoo 10.0**

**Comment by yelizariev** [comment]
Related to https://github.com/odoo/odoo/issues/20158#issuecomment-339630902
Fixed

**Comment by CGenie** [comment]
The way Odoo builds containers is fundamentally flawed.
You shouldn't base it on Debian:Stretch -- Docker is not some virtual machine where you install packages.
On the other hand, you should base it on something like python:3-stretch which has latest Python and then build on top of that installing packages like wkhtmltopdf and pip requirements. So build from source every time.
The way Docker works is you tailor the whole system to match your application and not vice versa by getting some system and fitting your application there :)
Or in other words -- treat Docker as a virtualenv for your application :)

**Comment by JosDeGraeve** [comment]
@CGenie i agree, but i don't see why this is related to this issue

**Comment by CGenie** [comment]
Because the fix in https://github.com/odoo/odoo/issues/20158#issuecomment-339630902 mentions Python 3.5 while if you built from python:3-stretch you would have 3.6 already.

**Comment by mamiu** [comment]
This bug still exists in the latest version of Odoo as described here: https://github.com/odoo/odoo/issues/20158#issuecomment-739628233
